# Generated by Django 3.2.9 on 2021-11-14 13:37

import django.core.files.storage
from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_author_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='default_pic',
            field=models.ImageField(default='default_pic', storage=django.core.files.storage.FileSystemStorage(location='/media/user_avatars/happy_tux.jpg'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_avatars/happy_tux.jpg', force_format=None, keep_meta=True, null=True, quality=100, size=[100, 100], upload_to='user_avatars'),
        ),
    ]
