# Generated by Django 3.2.9 on 2021-11-14 13:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_author_default_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='default_pic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/user_avatars/happy_tux.jpg'), upload_to=''),
        ),
    ]
