# Generated by Django 3.2.9 on 2021-11-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_author_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='points',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
    ]
